language: python
python:
  - "2.7"
  
install: 

  - sudo apt-get update
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - mongodb
  
script:
# command to run coveralls (test coverage) and run tests 
  - coverage run --omit=*/site-packages/*,*/tests/* -m unittest discover -s tests
  
after_success:
  coveralls

